name = input("what is your name ?: ")
age = int(input("what is your age ?: "))
height=float(input("how tall are you ?: "))
print("Hello "+name)
print("You are "+str(age)+" years old")
print("You are "+str(height)+"cm tall")